language: csharp
mono: none
dotnet: 2.0.0
dist: trusty
script:
 - dotnet restore
 - dotnet build
 - cd ./AStar.Tests
 - dotnet test
 - cd ../AStar.Core
 - dotnet pack -c Release --output nupkgs /p:PackageVersion=$MAJOR_VERSION_NUMBER.$MINOR_VERSION_NUMBER.$TRAVIS_BUILD_NUMBER
 - dotnet nuget push ./nupkgs/AStar.Core.$MAJOR_VERSION_NUMBER.$MINOR_VERSION_NUMBER.$TRAVIS_BUILD_NUMBER.nupkg -s https://www.nuget.org/api/v2/package -k $NUGET_API_KEY
